
= OGC® Geospatial Technology Trends

OGC Document 17-xxx +

''''

:doctype: book
:encoding: utf-8
:lang: en
:toc: macro
:toclevels: 3
:numbered:
:sectanchors:
:source-highlighter:


Copyright © 2019 Open Geospatial Consortium.

To obtain additional rights of use, visit http://www.opengeospatial.org/legal/[http://www.opengeospatial.org/legal/]

**Warning**

This document is not an OGC Standard.
This document is an OGC White Paper and is therefore not an official position of the OGC membership.
It is distributed for review and comment.
It is subject to change without notice and may not be referred to as an OGC Standard.
Further, an OGC White Paper should not be referenced as required or mandatory technology in procurements


Document type: OGC® White Paper +
Document stage:  +
Document language: English +

<<<

[discrete]
=== Geospatial Technology Forecasting Consultation

The Open Geospatial Consortium (OGC) tracks trends in Geospatial Technology. Trends are identified and characterized based on OGC processes that then drive action in consortium programs. Geospatial Tech Trends consultation is available to any organization that could benefit from roadmaps of geospatial technology.

[discrete]
=== Geospatial Technology Trends

In a survey of global CEOs, technology innovation is anticipated to have the most transformative effect on their business over the next five years (according to PWC Global). Identifying technology trends and developing roadmaps for their development and effect on markets is key to reducing risk and identifying business opportunities.
Geospatial technology advances with innovation in the application of location-based information and with general information technology innovations. OGC, as a consortium of over 500 of the most influential geospatial organizations, is the global forum for innovation and standards in geospatial technology. The OGC Technology Trends and roadmaps available to any organization to use in their business planning.

[discrete]
=== Disruptive Technologies Forecasting and Consultation

OGC’s Geospatial Technology Forecasting Process is based on “best of breed” for persistent forecasting of disruptive technologies (National Academies) and honed by its use across OGC Programs. The identification and characterization steps are performed on a quarterly basis and reviewed by the OGC Architecture Board and OGC Technical Committee. Trends are posted publicly and receive public review and comments.

Action is Taken in the OGC Programs and through Strategic Consultation on an NDA basis providing tailored discussions and forecasts for any organization affected by geospatial and location-based technology innovations.



include::preface.adoc[Preface]

include::chapter-01.adoc[]

include::chapter-02.adoc[]

include::chapter-03.adoc[]

include::chapter-04.adoc[]

include::chapter-05.adoc[]

include::chapter-06.adoc[]

include::chapter-07.adoc[]

include::chapter-08.adoc[]

include::appendix.adoc[]
